remote_theme: pages-themes/merlot@v0.2.0
title: Learning Celebration 1
description: Richard Powell - Spring 2024 - Intro to Linguistics

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
